### ISSUE TITLE
I need help and i try solved this

### ISSUE THREAD

**Issue by xaxole55** [OliBomby/SpellCastSolver#1]
I make all steps and this, you dont have executable .exe?
![image](https://github.com/OliBomby/SpellCastSolver/assets/122705252/7eeb7156-4828-498b-aa73-729976c7ef26)

**Comment by xaxole55** [comment]
![image](https://github.com/OliBomby/SpellCastSolver/assets/122705252/0d45fc4d-cea1-431f-a797-80126baa64d3)

**Comment by OliBomby** [comment]
I have compiled .exe in the Releases https://github.com/OliBomby/SpellCastSolver/releases/tag/v1.1.3
Can you share more information about your platform and PC?

**Comment by xaxole98** [comment]
![image](https://github.com/OliBomby/SpellCastSolver/assets/122705252/db42945d-65a8-4422-9d4c-0c32837d6fe0)
![image](https://github.com/OliBomby/SpellCastSolver/assets/122705252/dd685c4b-c304-4ee1-9ef4-58d20cb54d08)

**Comment by xaxole55** [comment]
![image](https://github.com/OliBomby/SpellCastSolver/assets/122705252/735b2929-463c-4bdc-b11c-b84ee320d195)

**Comment by xaxole55** [comment]
I have the requirements such as NET7.0 and what visual studio requested but it still maintains this.

**Comment by xaxole55** [comment]
I don't know if it's because of the colors or some graphic error, I tried to solve it using the code provided but currently we're still the same

**Comment by xaxole55** [comment]
I am a windows user, Intel Core 5 processor, 16 ram, windows 11 version 22h2

**Comment by xaxole55** [comment]
![image](https://github.com/OliBomby/SpellCastSolver/assets/122705252/69439508-f106-411f-adea-fe528521925b)

**Comment by xaxole55** [comment]
![image](https://github.com/OliBomby/SpellCastSolver/assets/122705252/3aa91910-ebc9-4f93-98ef-f511168ccaf4)

**Comment by OliBomby** [comment]
Probably an issue with osu!framework. Could try updating the package to see if that fixes it

**Comment by xaxole55** [comment]
How update dude?

**Comment by OliBomby** [comment]
Of you build it using visual studio you can in visual studio update the nuget packages in the nuget tab

**Comment by xaxole55** [comment]
![image](https://github.com/OliBomby/SpellCastSolver/assets/122705252/d89c322d-788b-46c9-9663-0e85d64e3e8e)
I think the problem is that these libraries must be installed manually from visual code for it to work, visual does not install them when running, the same thing happens in the .exe, it only works when I run it in visual studio code with the libraries installed manually via Nugget

**Comment by xaxole55** [comment]
![image](https://github.com/OliBomby/SpellCastSolver/assets/122705252/fc78a554-593b-4487-8572-cf43819d571b)
This was executed using visual studio code with the .sln file

**Comment by xaxole55** [comment]
![image](https://github.com/OliBomby/SpellCastSolver/assets/122705252/d8591621-7500-4387-9234-8ddf08d096e9)
And this one using the 64-bit Windows .exe:

**Comment by xaxole55** [comment]
I would like to support a solution for this and I started to follow you. I like your projects, I'm starting programming so I can't contribute much

**Comment by OliBomby** [comment]
Seems like you got it resolved.
The story about visual studio not installing libraries doesnt really make sense because it always restores nuget packages before build. You sure you didnt just update the packages and got it to work that way? That seems like the most likely explanation. You may make a PR with the fixes and ill merge them.

**Comment by xaxole55** [comment]
I'm sure, when you mentioned the nutget issue I opened it and I didn't have any of the mentioned libraries installed, I had to install them by "Click install"

![image](https://github.com/OliBomby/SpellCastSolver/assets/122705252/f6e8725d-eb3b-4ba1-b390-fdd97ff980e4)
Install these and everything started to work correctly except in the .exe version it only worked in .sln

**Comment by xaxole55** [comment]
In other words, I installed manually and the only thing I remember when compiling the code was that it asked to install Net Framework but the version of visual studio code, but when I ran the error mentioned, I thought of installing NetFramework7.0 and everything was still the same, the only thing that worked is to go to Projects -> Nutget Packages -> Install these packages that you did not have previously installed

**Comment by OliBomby** [comment]
Seems like you got it resolved.
The story about visual studio not installing libraries doesnt really make sense because it always restores nuget packages before build. You sure you didnt just update the packages and got it to work that way? That seems like the most likely explanation. You may make a PR with the fixes and ill merge them.

**Comment by OliBomby** [comment]
updated the package so it should be fixed now
